# Generated by Django 3.2.3 on 2021-08-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date_assigned',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
