# Generated by Django 3.2.3 on 2021-08-03 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_teacher'),
        ('answer', '0002_alter_answer_date_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
    ]
